[tools]
node = "latest"
bun = "latest"
rust = "latest"

[tasks.dev]
run = "bun run tauri dev"

[tasks.build]
run = "bun run tauri build"

[tasks."build:rpm"]
run = [{ task = "build", args = [
  "--bundles",
  "rpm",
] }]
